# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY DevExtremeAspNetCoreApp2/*.csproj ./DevExtremeAspNetCoreApp2/
RUN dotnet restore

# Copy everything else and build
COPY . .
WORKDIR /src/DevExtremeAspNetCoreApp2
RUN dotnet publish -c Release -o /app/publish

# Stage 2: Run
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DevExtremeAspNetCoreApp2.dll"]
